# Pipeline
PIPELINE_LOCK_FILE = "pipeline.lock"
PIPELINE_LOCK_TIMEOUT = 1

# SpiderFoot
SPIDERFOOT_TIMEOUT = 300

# Detection
DETECTION_TARGET_DELAY = 2

# Telegram
TELEGRAM_MAX_MESSAGE_LENGTH = 4000
TELEGRAM_MAX_RETRIES = 5
TELEGRAM_RETRY_DELAY = 2
TELEGRAM_REQUEST_TIMEOUT = 10